services:
  bot:
    # image: ghcr.io/nimon77/vogonplan:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: Europe/Paris
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ENGINE_URL: ${ENGINE_URL}
      # DEBUG: "true"
    restart: unless-stopped
  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -V"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Paris
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: unless-stopped

volumes:
  postgres_data:
